### ISSUE TITLE
go-openssl errors

### ISSUE THREAD

**Issue by vhar** [tarantool/go-tarantool#315]
Hi all.
I am running tarantool in docker-compose and getting this errors:
```
test-app     | go: downloading github.com/tarantool/go-openssl v0.0.8-0.20230307065445-720eeb389195
test-app     | go: downloading github.com/tarantool/go-iproto v0.1.0
test-app     | go: downloading github.com/vmihailenco/msgpack/v5 v5.3.5
test-app     | go: downloading github.com/vmihailenco/tagparser/v2 v2.0.0
test-app     | # github.com/tarantool/go-openssl
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:25:7: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:44:43: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:52:41: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:80:38: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:80:62: undefined: Conn
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:90:68: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:91:21: undefined: Conn
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:109:45: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:110:20: undefined: Conn
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:115:59: undefined: Ctx
test-app     | /go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/net.go:115:59: too many errors
test-app exited with code 1

```
What is wrong?

docker-compose.yaml
```
version: "3.9"

services:
  tarantool:
    image: tarantool/tarantool:latest
    container_name: test-tarantool
    hostname: tarantool
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: pass
    ports:
      - "${TARANTOOL_PORT}:3301"
    volumes:
      - ./tarantool:/var/lib/tarantool
    networks:
      - tarantool

  app:
    container_name: test-app
    image: golang:1.20-alpine
    working_dir: /usr/src/tarantool
    command: go run ./main.go
    volumes:
      - ./${GO_APP_HOMEDIR}:/usr/src/tarantool
    networks:
      - tarantool

networks:
  tarantool:
    driver: bridge
```

main.go
```
package main

import (
	"log"
	"github.com/tarantool/go-tarantool/v2"
)

func main() {
    conn, err := tarantool.Connect("tarantool:3301", tarantool.Opts{
            User: "admin",
            Pass: "pass",
    })
    if err != nil {
            log.Fatalf("Connection refused")
    }
    defer conn.Close()
    log.Println("Connection siccessful")
}

```
