### ISSUE TITLE
v2: broken build with `-tags go_tarantool_ssl_disable`

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/go-tarantool#357]
```
$ go test -tags go_tarantool_ssl_disable
# github.com/tarantool/go-tarantool/v2 [github.com/tarantool/go-tarantool/v2.test]
./ssl_disable.go:13:7: undefined: SslOpts
./ssl_disable.go:17:28: undefined: SslOpts
./dial.go:213:56: undefined: sslOpts
./export_test.go:19:26: undefined: sslOpts
FAIL	github.com/tarantool/go-tarantool/v2 [build failed]
```
It would be also nice to add a test step with the build type to CI for all test jobs, as example after that:
https://github.com/tarantool/go-tarantool/blob/b2b800b09a8047345b81b8cd9b0a7c258637d7ca/.github/workflows/testing.yml#L101-L104

```YAML
      - name: Run regression tests with disabled SSL
        run: |
          make test TAGS="go_tarantool_ssl_disable"
          make testrace TAGS="go_tarantool_ssl_disable"
```
