### ISSUE TITLE
Integer/Unsigned number no longer valid since 3.x+v2?

### ISSUE THREAD

**Issue by kokizzu** [tarantool/go-tarantool#398]
Previously this code inserting properly on tarantool 2.x + go-tarantool (v1)
```
row, err := conn.Insert("plans", arr)
```

but no longer work properly for tarantool 3.x + go-tarantool/v2
```
row, err := conn.Do(tarantool.NewInsertRequest(`plans`).
			Tuple(arr)).Get()
```

where input `arr` is:
![image](https://github.com/tarantool/go-tarantool/assets/1061610/2ddc3db0-4cba-468b-8474-f060492431b0)

and output `row` is:
![image](https://github.com/tarantool/go-tarantool/assets/1061610/f65a443e-670c-4419-9800-a4ff94533809)

but from terminal it's stored not as is:
```
SELECT * FROM plans WHERE id = 6;
---
- metadata:
  - name: id
    type: unsigned
  - name: tenantCode
    type: string
  - name: planType
    type: string
  - name: parentId
    type: unsigned
  - name: createdAt
    type: integer
  - name: createdBy
    type: unsigned
  - name: updatedAt
    type: integer
  - name: updatedBy
    type: unsigned
  - name: deletedAt
    type: integer
  - name: deletedBy
    type: unsigned
  - name: restoredBy
    type: unsigned
  - name: title
    type: string
  - name: description
    type: string
  - name: orgId
    type: unsigned
  - name: yearOf
    type: integer
  - name: budgetIDR
    type: unsigned
  - name: budgetUSD
    type: unsigned
  - name: quantity
    type: unsigned
  - name: unit
    type: string
  rows:
  - [6, '', 'program', 0, -20, 1, -20, 1, -32, 0, 0, 'ayaya', '', 0, -5, 1, 0, 4,
    'test']
...
```

for example that createdAt should be unix timestamp integer value but it's now stored as `-20`?
